name = "chirp"
main = "src/index.js"
compatibility_date = "2024-12-01"

[vars]
OLLAMA_BASE_URL = "https://ollama.com"
OLLAMA_MODEL = "gemini-3-flash-preview:cloud"

[[d1_databases]]
binding = "DB"
database_name = "chirp-db"
database_id = "a4673063-e0c3-4fec-9b85-faa4e5fb61c0"
